name: kit_2fa
description: "This package allows you to implement 2fa in any project quickly and easily."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  plugin_platform_interface: ^2.0.2
  otp: ^3.1.3
  bip39: ^1.0.6
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.13
  pinput: ^2.2.30
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
